In [1]:
#import libraries
import pandas as pd
import numpy as np
import tensorflow as tf
from transformers import BertTokenizer, TFBertForSequenceClassification
from transformers import InputExample, InputFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score

In [2]:
#get the model
model = TFBertForSequenceClassification.from_pretrained('./BERT/MonoBERTEmotion', num_labels = 5)
tokenizer = BertTokenizer.from_pretrained('./bert_model')
model.summary()

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at ./BERT/MonoBERTEmotion.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.

Model: "tf_bert_for_sequence_classification"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
bert (TFBertMainLayer)       multiple                  135193344
_________________________________________________________________
dropout_37 (Dropout)         multiple                  0
_________________________________________________________________
classifier (Dense)           multiple                  3845
=================================================================
Total params: 135,197,189
Trainable params: 135,197,189
Non-trainable params: 0
_________________________________________________________________

In [3]:
#read the data
test = pd.read_csv('EmotionTest.csv', encoding = 'utf-8')

In [4]:
test.head()

,Unnamed: 0,Unnamed: 0.1,ID,Tweet,Emotions
0,0,0,2018-En-00866,"@RanaAyyub @rajnathsingh Օ՜, թաքնված վրեժ և զա...",anger
1,1,1,2018-En-02590,"Ես այս ամենն անում եմ, որպեսզի համոզվեմ, որ դո...",joy
2,2,2,2018-En-03361,"եթե ոչ, ապա #teamchristine bc այն ամենը, ինչ Տ...",anger
3,3,3,2018-En-03230,Դա #հիանալի սկիզբ է #սկսնակների համար՝ անցնելո...,joy
4,4,4,2018-En-01143,Իմ լավագույն ընկերներն առաջին անգամ ինձ հետ վա...,fear

In [5]:
#create a polarity column and change the targets accordingly
test['Polarity'] = np.nan
for i in range(len(test)):
    if test['Emotions'][i] == 'anger':
        test['Polarity'][i] = 0
    elif test['Emotions'][i] == 'fear':
        test['Polarity'][i] = 1
    elif test['Emotions'][i] == 'joy':
        test['Polarity'][i] = 2
    elif test['Emotions'][i] == 'sadness':
        test['Polarity'][i] = 3
    else:
        test['Polarity'][i] = 4
test = test.drop('Emotions', axis = 1)

<ipython-input-5-a0aa1379ddaf>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['Polarity'][i] = 0
<ipython-input-5-a0aa1379ddaf>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['Polarity'][i] = 2
<ipython-input-5-a0aa1379ddaf>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['Polarity'][i] = 1
<ipython-input-5-a0aa1379ddaf>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['Polarity'][i] = 3
<ipython-input-5-a0aa1379ddaf>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['Polarity'][i] = 4

In [6]:
#predict
pred_sentences = test['Tweet']
tf_batch = tokenizer(list(pred_sentences), max_length = 128, padding = True, truncation = True, return_tensors = 'tf')
tf_outputs = model(tf_batch)
tf_predictions = tf.nn.softmax(tf_outputs[0], axis = -1)
labels = [0, 1, 2, 3, 4]
label = tf.argmax(tf_predictions, axis = 1)
label = label.numpy()
predictions = pd.Series(label, index = test.index)
print('Accuracy:', accuracy_score(test['Polarity'], predictions))
print('F-measure:', f1_score(test['Polarity'], predictions, average = None))
print('Recall:', recall_score(test['Polarity'], predictions, average = None))
print('Precision:', precision_score(test['Polarity'], predictions, average = None))

Accuracy: 0.7743682310469314
F-measure: [0.70542636 0.60215054 0.87223169 0.66257669 0.        ]
Recall: [0.68421053 0.65116279 0.8707483  0.69230769 0.        ]
Precision: [0.728      0.56       0.87372014 0.63529412 0.        ]

In [7]:
from sklearn.metrics.cluster import contingency_matrix
contingency_matrix(test['Polarity'], predictions)

array([[ 91,  12,  21,   8,   1],
       [  6,  28,   7,   2,   0],
       [ 13,   6, 256,  19,   0],
       [ 14,   3,   7,  54,   0],
       [  1,   1,   2,   2,   0]])

In [8]:
import pickle
with open('EmotionTestText.pickle', 'rb') as f:
    lemmatized_text = pickle.load(f)

In [9]:
tf_predictions

<tf.Tensor: shape=(554, 5), dtype=float32, numpy=
array([[0.87981033, 0.05415289, 0.0405109 , 0.00547917, 0.02004664],
       [0.00204022, 0.00197981, 0.9849223 , 0.00740052, 0.0036571 ],
       [0.78637516, 0.13120304, 0.05558843, 0.00500116, 0.02183221],
       ...,
       [0.37149763, 0.04411145, 0.35387027, 0.09931082, 0.13120984],
       [0.00733033, 0.0282471 , 0.7233638 , 0.208778  , 0.03228078],
       [0.00210433, 0.00221007, 0.9873433 , 0.00394196, 0.00440025]],
      dtype=float32)>

In [10]:
h = np.zeros((len(tf_predictions), 2))

for i in range(len(tf_predictions)):
    h[i][0] = tf_predictions[i][0] + tf_predictions[i][1] + tf_predictions[i][3]
    h[i][1] = tf_predictions[i][2] + tf_predictions[i][4]

In [11]:
x = []

for i in range(len(h)):
    r = h[i]
    if r[0] > r[1]:
        x.append(r[0] / r[1])
    else:
        x.append(r[1] / r[0])

In [12]:
x

[15.513219135260782,
 86.56148172044729,
 11.916452182770017,
 106.77922621001987,
 65.86950411003812,
 41.77938758331238,
 43.69825962049291,
 55.944537748455076,
 71.30136584130815,
 75.62923798592495,
 1.1317121162202055,
 11.622529421794345,
 147.14290342154416,
 112.23827517526095,
 30.421769835035256,
 124.73368658084898,
 6.964015707570512,
 159.36856350572293,
 159.00568752908623,
 11.650690601655098,
 1.0082285795955142,
 58.82492355166027,
 35.9499213025246,
 42.78252257747781,
 25.42558989990711,
 107.04350571792253,
 26.572779852424997,
 11.278404398857107,
 23.1388246880577,
 47.812735166635996,
 87.50961730747703,
 9.56503288187823,
 4.303438639970159,
 169.04150089309087,
 2.6173789984947007,
 26.97643005143169,
 170.61355788466938,
 64.05938526037401,
 83.62959015084556,
 40.35297961693775,
 25.954676339612956,
 6.193039515971367,
 168.44826655666188,
 93.96288375907096,
 1.165824183101626,
 157.66940917486397,
 9.179573310742013,
 14.269423309552812,
 45.36396175097927,
 7.119547819061079,
 71.1559620795804,
 52.599858190780324,
 17.73791989662279,
 153.49400026330727,
 1.802574636985072,
 1.3963624095465896,
 7.071559044670233,
 9.150212211224167,
 39.211979191399486,
 1.7449651472284995,
 77.47904807317585,
 7.629827950883084,
 1.5369293343402088,
 92.69102451071755,
 5.119809575971496,
 4.31544516800293,
 169.6627292212848,
 107.1393466752702,
 16.480768583316863,
 24.399210722576402,
 22.83325876806336,
 116.73816107118796,
 117.73546254880631,
 11.906468729505754,
 50.915161248398654,
 56.68488614972021,
 1.0096123445653333,
 82.12432257515115,
 10.346667766804206,
 6.048811455336868,
 15.78241557602662,
 1.1889865528517911,
 6.471013293974127,
 2.58018911358648,
 33.009081911534345,
 7.770691982868696,
 152.33201360898792,
 4.238823535840611,
 4.355411954765751,
 70.36745478209812,
 158.10341541131453,
 6.871824443256332,
 6.934815406880504,
 46.93437598854941,
 42.224114485621264,
 17.060928338266912,
 144.87972647907017,
 4.234227498465622,
 118.53221187981653,
 3.4258776622160045,
 127.03298464379675,
 8.001328962653977,
 2.8328660443432025,
 20.471961754881786,
 61.45933746013043,
 30.44625240413733,
 1.196659999217032,
 20.81361926314154,
 1.0848152982734232,
 81.4041918821567,
 14.11632899687915,
 29.508002746721335,
 141.24957473845754,
 112.06687418127903,
 146.26555815138096,
 67.22518773110168,
 144.56990798961624,
 19.307933157591528,
 3.6596556559636966,
 56.321721986883304,
 88.15670774894942,
 12.526321295186888,
 3.1646240157954297,
 73.47833733814234,
 40.10791637819124,
 131.38675942378927,
 4.344833375518225,
 142.00584147468334,
 1.7979081583558512,
 1.7699782121083816,
 38.35789367500776,
 134.21189814584824,
 6.48345093400312,
 3.1659769915722427,
 3.3880936474618886,
 13.147960638446232,
 1.7728973884161583,
 3.727226985336895,
 22.71755241735118,
 74.79699091226817,
 136.22001735598928,
 1.4613048560957802,
 4.73705441437073,
 33.83916736567246,
 1.12536652192012,
 143.2035065189886,
 20.655429111751708,
 20.310848329669263,
 68.47147118954892,
 112.55714503274278,
 8.365899564480378,
 47.095775530618575,
 16.98676010149251,
 1.1803140849049665,
 3.201552077527745,
 150.44259826848486,
 27.085343897496593,
 175.93037878631839,
 148.92232637937445,
 24.267935017269632,
 103.9273095272856,
 16.944022912907514,
 52.079631070180426,
 79.86626053105157,
 1.2391953575032166,
 29.898598063337218,
 13.747820533725854,
 80.68971337058692,
 2.1003159317547495,
 134.15949381301564,
 10.36251279172065,
 150.8352830146524,
 1.8573150762947144,
 88.87498279911543,
 1.3729777368417553,
 46.598719898318166,
 12.472305122051791,
 14.806044224701656,
 146.19071126658042,
 21.669208564890017,
 53.25496425991569,
 1.0657125053113508,
 81.95538816961918,
 11.93613554200407,
 47.95204645964242,
 17.98138344699682,
 120.50637479111776,
 29.209085206503143,
 7.221283031775041,
 44.25661900176147,
 67.42630799264795,
 40.97621651611539,
 7.1271117786331315,
 1.1142459427276963,
 57.79536265747968,
 22.544289255486525,
 128.4725994373822,
 114.07001968877756,
 3.9435834095214983,
 16.482689894821373,
 96.3848646401331,
 48.25318665381923,
 21.23862587428751,
 94.4026783143963,
 82.7386869829901,
 1.8978869553772317,
 13.369951387368424,
 23.70671371489733,
 14.471914288154817,
 6.863043059765647,
 25.27439523278596,
 27.570976830126263,
 2.3627929202064033,
 182.79514513549847,
 33.70953792634301,
 1.3387868547281656,
 45.39257802913567,
 7.926333289749493,
 81.46453149420344,
 1.7430736120778043,
 189.34511298608507,
 72.69072970747696,
 11.361103090963395,
 21.496841974700263,
 2.916431011517339,
 109.84610365880097,
 70.36051466890927,
 25.104927364172628,
 70.06686391911097,
 9.916838666857537,
 93.87466430241791,
 133.01899714092733,
 6.184896387887758,
 155.45562731643517,
 5.028877111422826,
 18.044360974374953,
 5.87684953596107,
 43.1857128465997,
 51.3655606910639,
 1.3818653882151495,
 8.331069932211982,
 8.377793857196318,
 44.3137791244825,
 160.7363211837245,
 18.568778158296336,
 79.82046736905554,
 42.4696819586108,
 102.73138588311126,
 10.122321424132085,
 44.78692208893157,
 7.447378272486255,
 37.839404348165786,
 1.284961695346921,
 31.136251388191955,
 89.709809524421,
 15.818682962844894,
 40.38038286289148,
 109.02797144897205,
 4.381711655359348,
 27.38838598873498,
 34.690879187248974,
 27.02227455696414,
 19.076811786494098,
 132.55495631397665,
 2.155444595127189,
 11.94806485757273,
 149.49096844045312,
 45.189328369496145,
 63.29419091032768,
 2.4164607473007162,
 3.241787378360209,
 8.478926793935871,
 1.6492319425978152,
 1.6966121688166258,
 21.30533757499739,
 147.32984108038812,
 87.43535493750137,
 2.3695063717933165,
 146.10839455304938,
 32.222146094760205,
 50.649557092352374,
 9.43240916879912,
 113.03233392621756,
 11.824230733804525,
 2.78646203137011,
 4.2204964619667455,
 19.41790640508932,
 8.957410239896658,
 4.9401108804028615,
 80.59011040489902,
 6.417792922371174,
 74.2222942711526,
 1.2360939011288015,
 58.50819182606394,
 8.886314301721391,
 18.707762643569048,
 8.96929572964228,
 62.311994930048776,
 10.311312084641258,
 59.012082543273024,
 2.1690532167212857,
 92.97334348792835,
 41.77115737419787,
 17.66961293213157,
 31.067012341003892,
 180.11061941230486,
 64.9849035227326,
 1.9634767737398762,
 4.01805093104696,
 89.13583200552496,
 13.07837483160889,
 62.22900009610293,
 23.830683026482717,
 140.40344333013803,
 50.300237203581524,
 25.073067594139115,
 142.58082685665792,
 121.58247320403747,
 1.1985024115467,
 185.0760136952995,
 160.04918431240617,
 11.22429541293311,
 1.775130012769702,
 40.58589460543771,
 88.69666251545843,
 58.79665628456956,
 50.163613107056385,
 38.1278363751304,
 14.228040537090811,
 7.825410406296645,
 170.61496904793356,
 32.6110369862849,
 29.911245323622374,
 1.3175903502615043,
 12.845482120228942,
 1.508003060032013,
 87.22018410734884,
 6.706025361991828,
 2.918409515608392,
 179.9476231266198,
 174.78698889590677,
 5.657427820345409,
 72.71274601452133,
 106.34252965651022,
 60.382037150205484,
 8.653934699258896,
 4.1161244964504045,
 37.001430457193486,
 75.68598094530704,
 14.131811332815854,
 17.637209508998,
 83.81984168211801,
 74.94491043985641,
 1.0657244595042177,
 9.67823455281448,
 68.63272277422274,
 66.4060393251197,
 10.619093430530683,
 4.602763692710232,
 181.74999000079822,
 20.332366510318845,
 98.21610322581598,
 1.3088358390815529,
 9.667327471423167,
 24.34050111676047,
 71.33111716066192,
 2.730419550643293,
 74.8816936908847,
 53.513048302662625,
 112.00476207515676,
 169.21018437849142,
 32.06585296076751,
 47.38400094520182,
 8.17408277101083,
 174.2443826716404,
 157.74278636937862,
 132.75328680572795,
 2.2043387605402134,
 69.78626517730126,
 81.05654076798628,
 7.42290793684582,
 70.801941071334,
 76.11626240082002,
 38.06406359325649,
 126.41102424880027,
 171.34520452497324,
 137.36224588347432,
 59.44437881907205,
 3.1840366241243987,
 22.885642389103037,
 102.05709584368871,
 126.1919968935892,
 1.0478616372698475,
 39.324398291486645,
 61.215608399388124,
 1.7994777389981496,
 6.903948036346291,
 103.24242851997441,
 5.244234267236346,
 13.186331043913794,
 7.556603066302245,
 33.958176580593744,
 2.637319453435669,
 76.52275146913513,
 38.79525953414565,
 152.77582268733335,
 4.093573662584174,
 6.360192037258053,
 131.2436604611943,
 45.72240043471859,
 2.8429155896756835,
 143.56271571814858,
 14.286254131270622,
 5.918839438153131,
 30.440107594359986,
 74.17119967919243,
 34.904822394264976,
 1.969486034373876,
 4.193958436173287,
 4.2742655101282,
 45.97992555960246,
 156.31327932019633,
 3.7317223817430123,
 2.4335809585148263,
 7.735141255645364,
 10.906885466550287,
 50.04010225685713,
 154.40551026227007,
 33.53511405824419,
 1.1504091774908864,
 25.638891615166482,
 10.184553755263629,
 68.55897032123887,
 17.543345427285487,
 24.502565975369905,
 1.1501154725531857,
 48.29990219374894,
 75.92908785150863,
 1.9475833403682403,
 33.45424534407692,
 4.189935854365652,
 1.0752603381009158,
 123.68514099427912,
 46.20973654854126,
 26.923478244044965,
 28.98853369410151,
 145.1792329013406,
 12.66210047707208,
 33.66826028345181,
 38.80135054657726,
 4.359647587858449,
 175.29948592396792,
 1.2765738257094017,
 97.35763687044907,
 4.740888868243808,
 66.79945067972669,
 162.17375617348537,
 3.3543177256513843,
 176.7569911384878,
 20.551984889268418,
 1.0427610000938146,
 60.9535439829341,
 15.794092088287218,
 12.897488593552747,
 39.676473797141504,
 102.77965905113885,
 2.357011360006259,
 76.82611921696797,
 6.813690899299946,
 5.613799196081048,
 50.883106112169266,
 65.98679156906327,
 120.25327476694066,
 14.760308898842744,
 5.110496520208323,
 143.30235377559285,
 2.1551747759299222,
 2.9037857410942047,
 4.300816265274366,
 1.2272022361741202,
 8.052628355674143,
 188.7499479785227,
 37.086119159753004,
 1.094806340600113,
 89.21522257932362,
 1.1628863698727752,
 179.55329318279348,
 21.7865891640141,
 8.493489330429549,
 141.1691299130481,
 8.38539945086585,
 3.653060352837091,
 2.3135161237284025,
 21.251774166367074,
 45.71894088014937,
 86.361404376915,
 93.76783043177565,
 1.4707678301255271,
 29.17986270877033,
 72.27467824748695,
 3.3721246572391093,
 2.422047886840736,
 93.84715777449198,
 5.070262826642816,
 95.65348184701135,
 13.350125252991798,
 1.111077864014706,
 7.860362759494453,
 6.286983421426133,
 119.32646328767522,
 75.05543500318922,
 3.696704622598593,
 2.2081988633288847,
 23.792264579416567,
 5.565800046629612,
 3.678468631870751,
 1.5215622572236782,
 104.39180074551705,
 3.5656547287505522,
 4.735803921917212,
 1.641693950068108,
 4.232930890145112,
 78.69633528371595,
 5.547373796286305,
 2.8729835011923868,
 1.089302230357767,
 24.543552855799238,
 88.22144137917338,
 92.46184316604399,
 6.072949687192411,
 1.4385226497184005,
 2.8022954442850954,
 7.870236190082178,
 85.3226758423308,
 113.52782116564875,
 3.068209650131084,
 9.322150276650143,
 1.0147813776653973,
 36.13184434572207,
 65.24473110509953,
 1.5706847966270943,
 4.318763141098775,
 11.743153975452826,
 4.716559818320899,
 85.24573842380538,
 139.36285252422365,
 1.031409002596712,
 10.576469991578412,
 71.43292939680164,
 8.083942955500245,
 134.721650610414,
 1.0615152266556112,
 3.092399600815079,
 120.11870051015194]

In [13]:
possibility = pd.Series(x, index = test.index)

In [14]:
index = []
for i in range(len(predictions)):
    if predictions[i] != test['Polarity'][i]:
        index.append(i)

y = {'Text': test['Tweet'].loc[index], 'Label': test['Polarity'].loc[index], 'Prediction': predictions[index], 'Possibility': possibility[index]}
summary = pd.DataFrame(y)
summary

,Text,Label,Prediction,Possibility
4,Իմ լավագույն ընկերներն առաջին անգամ ինձ հետ վա...,1.0,0,65.869504
10,"Օ, մելամաղձոտ կատակոմբները արագ թափառեցին Մորգ...",3.0,2,1.131712
11,"#LouiseLinton - ատողները ատում են, շարունակելո...",3.0,0,11.622529
14,"#RIPBiwott Կարծում եմ, որ Ռոբերտ Ուկոսի հոգին ...",0.0,2,30.421770
16,@GarfieldLineker @TimCRoberts *իր մեջքին: Ներո...,3.0,0,6.964016
...,...,...,...,...
536,@LogicIsPowerful Ոչ բոլորն են վատը: Բայց ես պա...,3.0,0,9.322150
537,"Այն ամենը, ինչ ես պատվիրում եմ առցանց, պարզապե...",0.0,2,1.014781
541,@uzalu_ @Veeh_Ro Ի՜նչ անուրախ քիթ է։,0.0,3,4.318763
543,Այսօրվա համար շատ կարևոր բան. \n\nՄի՛ ահաբեկեք...,3.0,1,4.716560
546,@kamaalrkhan Ո՞ր #չուտիայի #արտադրողն է #ներդն...,0.0,2,1.031409

In [15]:
def get_index(cont, thr):
    ind = []
    for i in range(len(cont)):
        if cont[i] < thr:
            ind.append(i)
    return ind

In [16]:
low_index = get_index(possibility, 1.3)

In [17]:
low_index

[10,
 20,
 44,
 76,
 81,
 106,
 108,
 144,
 153,
 164,
 181,
 193,
 252,
 292,
 318,
 353,
 392,
 429,
 435,
 441,
 452,
 460,
 479,
 483,
 485,
 506,
 525,
 537,
 546,
 551]

In [18]:
len(test)

554

In [19]:
len(low_index)

30

In [20]:
with open('anger_contribution.pickle', 'rb') as f:
    anger_contribution = pickle.load(f)
    
with open('fear_contribution.pickle', 'rb') as f:
    fear_contribution = pickle.load(f)

with open('joy_contribution.pickle', 'rb') as f:
    joy_contribution = pickle.load(f)
    
with open('sadness_contribution.pickle', 'rb') as f:
    sadness_contribution = pickle.load(f)

with open('surprise_contribution.pickle', 'rb') as f:
    surprise_contribution = pickle.load(f)
    
with open('positive_adverb.pickle', 'rb') as f:
    positive_adverb = pickle.load(f)
    
with open('negative_adverb.pickle', 'rb') as f:
    negative_adverb = pickle.load(f)

In [21]:
anger_contribution

                  Word  Count  Contribution
0           ազգայնամոլ      0      0.500000
1    ազգայնամոլություն      0      0.500000
2       ազգանվանանակից      0      0.500000
3           ազգություն      0      0.500000
4                 ակոս      0      0.500000
..                 ...    ...           ...
612        օրենսդրական      0      0.500000
613    օրենականություն      0      0.500000
614          օրենսգիրք      0      0.500000
615           օրինագիծ      1      0.731059
616           օրինաչափ      0      0.500000

[617 rows x 3 columns]

In [22]:
fear_contribution

                    Word  Count  Contribution
0     միանգամայն բավարար      0      0.500000
1                 լիառատ      0      0.500000
2                    նոր    426      1.000000
3                թթվային      0      0.500000
4                   ագահ     11      0.999983
...                  ...    ...           ...
6535              օրորել      1      0.731059
6536           օրհասական      0      0.500000
6537            ֆանտազիա      1      0.731059
6538             ֆեդերալ      1      0.731059
6539           ֆեդերատիվ      0      0.500000

[6540 rows x 3 columns]

In [23]:
joy_contribution

                Word  Count  Contribution
0        ագահություն      0      0.500000
1            ագրեսիվ      1      0.731059
2              ազդու      0      0.500000
3           ակամայից      2      0.880797
4               աղբի      0      0.500000
..               ...    ...           ...
528           օճառոտ      0      0.500000
529        օճառ քսել      0      0.500000
530         օրացույց      0      0.500000
531         օրինակել      2      0.880797
532  օրինաչափություն      0      0.500000

[533 rows x 3 columns]

In [24]:
sadness_contribution

                 Word  Count  Contribution
0    ազգաբնակչություն      0      0.500000
1           ախտորոշել      0      0.500000
2                ածել    105      1.000000
3            ականանետ      0      0.500000
4               ակամա      6      0.997527
..                ...    ...           ...
474            քրոնիկ      1      0.731059
475          օդափոխել      0      0.500000
476             օթյակ      0      0.500000
477        օջախ(տուն)      0      0.500000
478            օրական      2      0.880797

[479 rows x 3 columns]

In [25]:
surprise_contribution

                Word  Count  Contribution
0           ազատարար      0      0.500000
1              ազդել      5      0.993307
2            ազդեցիկ      0      0.500000
3       ազդեցություն      3      0.952574
4           ազնվաքիս      0      0.500000
...              ...    ...           ...
997             օղակ      3      0.952574
998         օսմանյան      0      0.500000
999           օրհնել      3      0.952574
1000          օրորոց      0      0.500000
1001  ֆիզկուլտուրնիկ      0      0.500000

[1002 rows x 3 columns]

In [26]:
positive_adverb

['ամբողջությամբ',
 'անպայման',
 'խնդրեմ',
 'նույնիսկ',
 'դեռ',
 'դեռևս',
 'արդեն',
 'անկասկած',
 'շատ',
 'բարձրաձայն',
 'հատկապես',
 'պասսիվորեն',
 'հեշտորեն',
 'հեշտությամբ',
 'քննադատաբար',
 'քաղաքավարիորեն',
 'համեստորեն',
 'զգույշ',
 'քաոսայնորեն',
 'հերոսաբար',
 'սառնորեն',
 'ամբողջովին',
 'ամբողջովին ',
 'անխտիր',
 'ավելի լավ',
 'ավելի քիչ',
 'բոլորովին',
 'զարմանալիորեն',
 'էլ',
 'ինչքան էլ որ',
 'լիովին',
 'կատարելապես',
 'հաճախ',
 'համապատասխանաբար',
 'հենց',
 'հետեւաբար',
 'հոգեպես',
 'միանգամայն',
 'շուրջ',
 'որքան էլ որ',
 'պարզապես',
 'վճռականորեն',
 'տրամաբանորեն',
 'ուղակի']

In [27]:
negative_adverb

['ուղղակի',
 'երբեք',
 'չ-',
 'շուտով',
 'շուտ',
 'հազվադեպ',
 'իհարկե',
 'անշուշտ',
 'սովորաբար',
 'չափազանց',
 'սաստիկ',
 'քիչ',
 'սակավ',
 'ֆիզիկապես',
 'ֆիզիկորեն',
 'այժմ',
 'անմիջապես',
 'հիմա',
 'պատահաբար']

In [28]:
test.loc[low_index]

,Unnamed: 0,Unnamed: 0.1,ID,Tweet,Polarity
10,10,10,2018-En-01472,"Օ, մելամաղձոտ կատակոմբները արագ թափառեցին Մորգ...",3.0
20,20,23,2018-En-01237,#Թրամփի միակ #մտահոգությունը անձնական #շահույթ...,0.0
44,44,63,2018-En-00685,"Ուրախ եմ, որ մեկ անգամ թիմով խաղացինք tgt: Մտա...",3.0
76,76,107,2018-En-03321,"#Աշխարհ գիտե՞ս, թե որն է տարբերությունը #հարբա...",2.0
81,81,119,2018-En-01525,Շնորհակալություն հայտնելու կարիք չկա: 😃,2.0
106,106,159,2018-En-00621,"արագ նշում insta story-ների մասին, թե ինչպես է...",0.0
108,108,165,2018-En-02533,"Մի նշիր ինձ նկարներում որպես «նախ ընտանիքը», ե...",0.0
144,144,219,2018-En-01458,"Հիշեք, որ ձեր ինքնությունը Քրիստոսի մեջ է: Մեր...",1.0
153,153,237,2018-En-02101,"Tipoftheday. Մի շեղվեք նրանց կողմից, ովքեր մեղ...",2.0
164,164,259,2018-En-00755,Ինչպե՞ս եք վերաբերվում @Snapchat-ի նոր ֆունկցի...,2.0
181,181,284,2018-En-00459,Wtf shawty ass on 😤,0.0
193,193,299,2018-En-01269,"Ես սիրում եմ տեսնել @yeahlizzy-ին, քանի որ դա ...",2.0
252,252,390,2018-En-00492,"Չափազանց շատ կոֆեին, և ես հոգում եմ: #ցնցումնե...",1.0
292,292,452,2018-En-00006,Իմ նոր սիրելի #ֆիլմը՝ առանց կասկածի ստվերի #Ok...,2.0
318,318,488,2018-En-03231,"@EspionageLove -- շուտով կանգ առեք, նրա մարմին...",2.0
353,353,543,2018-En-02910,@vvxaii ես ամաչում եմ քեզ ընկեր անվանել քո քու...,2.0
392,392,617,2018-En-00481,@KicchaSudeep Խոսքեր չկան պարոն... Շնորհակալու...,2.0
429,429,680,2018-En-03680,@theAliceRoberts @FryRsquared @AdamRutherford ...,0.0
435,435,689,2018-En-02408,Ջուլիան և ես վերջապես կկարողանանք հանդիպել PTX...,2.0
441,441,698,2018-En-00092,Ի դեպ...եթե չգիտեիք...Ջոշուասը դուրս կգա այս ե...,2.0
452,452,717,2018-En-00575,#WalkingSideBySide. հիանալի ամուսնություններ՝ ...,3.0
460,460,731,2018-En-01820,Աֆրիդի !!! 100 զեղչ 42 !! #խելագար,0.0
479,479,762,2018-En-02222,Ամբողջովին վախեցեք այս գալիք արդյունքների համար:,1.0
483,483,768,2018-En-01889,"@itskaiouji Noooo, Sunbae-nim! Ինձ այդպես մի ծ...",0.0
485,485,771,2018-En-02255,@iamjpk NameisNani ինչ PhD! էեսավ գատիգա,2.0
506,506,804,2018-En-00818,"Ես միայն մազերս եմ կտրում, որպեսզի կարողանամ փ...",2.0
525,525,833,2018-En-01291,@narendramodi @AmitShahOffice @OfficeOfRG @aru...,1.0
537,537,855,2018-En-03875,"Այն ամենը, ինչ ես պատվիրում եմ առցանց, պարզապե...",0.0
546,546,872,2018-En-01302,@kamaalrkhan Ո՞ր #չուտիայի #արտադրողն է #ներդն...,0.0
551,551,881,2018-En-01993,@BadHombreNPS @SecretaryPerry Եթե սա ինձ այդքա...,0.0

In [29]:
lemmatized_text = lemmatized_text.reset_index()

In [30]:
lemmatized_text

     index                                                  0
0        0  [օ, թաքնվել, վրեժ, և, զայրույթ, հիշել, ժամանակ...
1        1        [ամենը, անել, համոզվել, դու, ժպտալ, եղբայր]
2        2  [ոչ, տանել, անել, սադրել, թվիթեր, ստվերային, բ...
3        3  [հիանալի, սկիզբ, սկսնակ, անցնել, ավտ, առևտուր,...
4        4  [լավ, ընկեր, առաջին, անգամ, հետ, վարել, մեքենա...
..     ...                                                ...
549    877  [երբեք, զղջա, բան, որ, ժամանակին, ստիպել, ժպտա...
550    880  [մեկը, կողմ, խորապես, սիրել, լինել, ուժ, տալ, ...
551    881                                 [չ, ծիծաղել, թվիթ]
552    882                         [ուրախ, դիտել, երեկո, գալ]
553    885  [իսկապես, շոյվել, և, ուրախ, լսել, լրացում, բլո...

[554 rows x 2 columns]

In [31]:
ang_count = []
fea_count = []
joy_count = []
sad_count = []
sur_count = []
data = lemmatized_text.iloc[low_index]

for i in low_index:
    words = data[0][i]
    ang = 0
    fea = 0
    joy = 0
    sad = 0
    sur = 0
    for j in range(len(words)):
        if words[j] in anger_contribution['Word'].values:
            ang += 1
        elif words[j] in fear_contribution['Word'].values:
            fea += 1
        elif words[j] in joy_contribution['Word'].values:
            joy += 1
        elif words[j] in sadness_contribution['Word'].values:
            sad += 1
        elif words[j] in surprise_contribution['Word'].values:
            sur += 1
    ang_count.append(ang)
    fea_count.append(fea)
    joy_count.append(joy)
    sad_count.append(sad)
    sur_count.append(sur)

In [32]:
ang_count

[0,
 0,
 0,
 0,
 1,
 2,
 0,
 2,
 0,
 1,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0]

In [33]:
fea_count

[2,
 8,
 12,
 3,
 1,
 3,
 6,
 6,
 8,
 4,
 0,
 5,
 1,
 9,
 2,
 3,
 1,
 3,
 2,
 6,
 5,
 0,
 1,
 0,
 0,
 2,
 0,
 1,
 0,
 1]

In [34]:
joy_count

[0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [35]:
sad_count

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [36]:
sur_count

[0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 2,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0]

In [37]:
def found_something(ind, words, window, adverb):
    a = ind - 1
    found_a = False
    count_a = 0
    while a >= 0 and found_a == False and count_a <= window:
        if words[a] in adverb:
            found_a = True
        a = a - 1
        count_a = count_a + 1
    b = ind + 1
    found_b = False
    count_b = 0
    while b < len(data[0][i]) and found_b == False and count_b <= window:
        if words[b] in adverb:
            found_b = True
        b = b + 1
        count_b = count_b + 1
    return found_a, found_b

In [38]:
anger_emotion = []
fear_emotion = []
joy_emotion = []
sadness_emotion = []
surprise_emotion = []

for i in low_index:
    words = data[0][i]
    ang_words = []
    fea_words = []
    joy_words = []
    sad_words = []
    sur_words = []
    ang_scores = np.array([])
    fea_scores = np.array([])
    joy_scores = np.array([])
    sad_scores = np.array([])
    sur_scores = np.array([])
    
    for j in range(len(words)):
        if words[j] in anger_contribution['Word'].values:
            ang_ind = np.where(anger_contribution['Word'] == words[j])[0]
            ang_cont = anger_contribution['Contribution'][ang_ind]
            ang_words.append([words[j], ang_cont])
        elif words[j] in fear_contribution['Word'].values:
            fea_ind = np.where(fear_contribution['Word'] == words[j])[0]
            fea_cont = fear_contribution['Contribution'][fea_ind]
            fea_words.append([words[j], fea_cont])
        elif words[j] in joy_contribution['Word'].values:
            joy_ind = np.where(joy_contribution['Word'] == words[j])[0]
            joy_cont = joy_contribution['Contribution'][joy_ind]
            joy_words.append([words[j], joy_cont])
        elif words[j] in sadness_contribution['Word'].values:
            sad_ind = np.where(sadness_contribution['Word'] == words[j])[0]
            sad_cont = sadness_contribution['Contribution'][sad_ind]
            sad_words.append([words[j], sad_cont])
        elif words[j] in surprise_contribution['Word'].values:
            sur_ind = np.where(surprise_contribution['Word'] == words[j])[0]
            sur_cont = surprise_contribution['Contribution'][sur_ind]
            sur_words.append([words[j], sur_cont])
            
    for k in range(len(ang_words)):
        word = ang_words[k][0]
        c = ang_words[k][1]
        ind = data[0][i].index(word)
        pos_found = found_something(ind, words, 4, positive_adverb)
        if pos_found[0] == True or pos_found[1] == True:
            g = 2
        else:
            g = 1
        neg_found = found_something(ind, words, 3, negative_adverb)
        if neg_found[0] == True or neg_found[1] == True:
            f = 1
        else:
            f = -1
        ang_scores = np.append(ang_scores, g * f * c)
        
    for l in range(len(fea_words)):
        word = fea_words[l][0]
        c = fea_words[l][1]
        ind = data[0][i].index(word)
        pos_found = found_something(ind, words, 4, positive_adverb)
        if pos_found[0] == True or pos_found[1] == True:
            g = 2
        else:
            g = 1
        neg_found = found_something(ind, words, 3, negative_adverb)
        if neg_found[0] == True or neg_found[1] == True:
            f = 1
        else:
            f = -1
        fea_scores = np.append(fea_scores, g * f * c)

    for m in range(len(joy_words)):
        word = joy_words[m][0]
        c = joy_words[m][1]
        ind = data[0][i].index(word)
        pos_found = found_something(ind, words, 4, positive_adverb)
        if pos_found[0] == True or pos_found[1] == True:
            g = 2
        else:
            g = 1
        neg_found = found_something(ind, words, 3, negative_adverb)
        if neg_found[0] == True or neg_found[1] == True:
            f = 1
        else:
            f = -1
        joy_scores = np.append(joy_scores, g * f * c)
        
    for n in range(len(sad_words)):
        word = sad_words[n][0]
        c = sad_words[n][1]
        ind = data[0][i].index(word)
        pos_found = found_something(ind, words, 4, positive_adverb)
        if pos_found[0] == True or pos_found[1] == True:
            g = 2
        else:
            g = 1
        neg_found = found_something(ind, words, 3, negative_adverb)
        if neg_found[0] == True or neg_found[1] == True:
            f = 1
        else:
            f = -1
        sad_scores = np.append(sad_scores, g * f * c)
    
    for o in range(len(sur_words)):
        word = sur_words[o][0]
        c = sur_words[o][1]
        ind = data[0][i].index(word)
        pos_found = found_something(ind, words, 4, positive_adverb)
        if pos_found[0] == True or pos_found[1] == True:
            g = 2
        else:
            g = 1
        neg_found = found_something(ind, words, 3, negative_adverb)
        if neg_found[0] == True or neg_found[1] == True:
            f = 1
        else:
            f = -1
        sur_scores = np.append(sur_scores, g * f * c)
    
    anger_emotion.append(np.sum(ang_scores))
    fear_emotion.append(np.sum(fea_scores))
    joy_emotion.append(np.sum(joy_scores))
    sadness_emotion.append(np.sum(sad_scores))
    surprise_emotion.append(np.sum(sur_scores))

In [39]:
for i in range(len(low_index)):
    scores = np.array([anger_emotion[i], fear_emotion[i], joy_emotion[i], sadness_emotion[i], surprise_emotion[i]])
    maximum_index = np.argmax(scores)
    predictions[low_index[i]] = maximum_index

In [40]:
print('Accuracy:', accuracy_score(test['Polarity'], predictions))
print('F-measure:', f1_score(test['Polarity'], predictions, average = None))
print('Recall:', recall_score(test['Polarity'], predictions, average = None))
print('Precision:', precision_score(test['Polarity'], predictions, average = None))

Accuracy: 0.7707581227436823
F-measure: [0.69784173 0.60416667 0.8712522  0.67080745 0.        ]
Recall: [0.72932331 0.6744186  0.84013605 0.69230769 0.        ]
Precision: [0.66896552 0.54716981 0.9047619  0.65060241 0.        ]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [41]:
contingency_matrix(test['Polarity'], predictions)

array([[ 97,  13,  15,   8],
       [  8,  29,   4,   2],
       [ 23,   7, 247,  17],
       [ 16,   3,   5,  54],
       [  1,   1,   2,   2]])